const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
function engine(){
 const values=new Map();let seed=123456;const math=Object.create(Math);math.random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};const context=vm.createContext({console,Date,Math:math,structuredClone,localStorage:{setItem:(k,v)=>values.set(k,v),getItem:k=>values.get(k)||null,removeItem:k=>values.delete(k)}});
 for(const file of ['data/CountriesDB','data/RegionsDB','data/NeighborsDB','data/CitiesDB','UnitsDB','Tech','Economy','GameData','AI','GameLoop'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../js',file+'.js'),'utf8'),context);
 return Object.assign(vm.runInContext('({GameData,AI,SaveGame,GameLoop,RegionsDB,UnitsDB,DEVELOPMENT,POLICIES,Economy,RESOURCES,ECONOMY,Tech,TECH_TREE,MODERNIZATION})',context),{localStorage:context.localStorage});
}
test('casualties are invariant under splitting an attack into orders',()=>{
 const {GameData}=engine();const fight=split=>{const d=new GameData('UA',{scenario:'war2024'});for(const id of ['UA-1','RU-19']){d.regions[id].army=d.emptyArmy();d.regions[id].army.infantry=10;}
 for(let i=0;i<(split?10:1);i++)assert.equal(d.queueAttack('UA-1','RU-19',{infantry:split?1:10}).ok,true);
 const log=d.processOrders().logs.find(l=>l.losses);return JSON.stringify(log.losses);};assert.equal(fight(true),fight(false));assert.ok(JSON.parse(fight(true)).attacker.infantry>0);
});
test('orders validate ownership, adjacency, funds, finite integer counts and reservations',()=>{
 const {GameData}=engine(),d=new GameData('UA');for(const n of [NaN,Infinity,-1,0,0.5])assert.equal(d.queueRecruitment('UA-1','infantry',n).ok,false);
 assert.ok(Number.isFinite(d.countries.UA.money));assert.equal(d.queueMovement('UA-1','US-1',{infantry:1}).ok,false);assert.equal(d.queueAttack('UA-1','RU-19',{infantry:1}).ok,false);
 const n=d.regions['UA-1'].army.infantry,to=d.getValidMoveTargets('UA-1')[0];assert.equal(d.queueMovement('UA-1',to,{infantry:n}).ok,true);assert.equal(d.queueMovement('UA-1',to,{infantry:1}).ok,false);
 const money=d.countries.UA.money;assert.equal(d.queueRecruitment('UA-1','tanks',1).ok,true);d.cancelOrder('recruitment',0);assert.equal(d.countries.UA.money,money);assert.equal(d.cancelOrder('movements',NaN),null);
});
test('construction reserves money, completes once, cancels or refunds lost territory',()=>{
 const {GameData,DEVELOPMENT}=engine(),d=new GameData('UA'),r=d.regions['UA-1'];const old=r.resources.agro,money=d.countries.UA.money;
 assert.equal(d.invest(r.id,'agro').ok,true);assert.equal(d.invest(r.id,'oil').ok,false);d.processProjects();assert.equal(r.resources.agro,old);d.processProjects();assert.equal(r.resources.agro,old+DEVELOPMENT.agro.gain);d.processProjects();assert.equal(r.resources.agro,old+15);
 assert.equal(d.invest(r.id,'industry').ok,true);assert.equal(d.cancelProject(r.id),true);assert.equal(d.countries.UA.money,money-DEVELOPMENT.agro.cost);
 d.invest(r.id,'oil');d.setOwner(r.id,'RU');d.processProjects();assert.equal(d.countries.UA.money,money-DEVELOPMENT.agro.cost);
});
test('policies change real budget with an influence cost and cooldown',()=>{
 const {GameData,Economy}=engine(),d=new GameData('UA');const base=Economy.flows(d,'UA').goods.prod,sales=d.countryBalance('UA').sales;assert.equal(d.setPolicy('UA','production').ok,true);assert.ok(Economy.flows(d,'UA').goods.prod>base);assert.ok(d.countryBalance('UA').sales>sales);assert.equal(d.countries.UA.influence,45);assert.equal(d.setPolicy('UA','social').ok,false);d.turn+=3;assert.equal(d.setPolicy('UA','social').ok,true);assert.ok(d.countryBalance('UA').social>0);
});
test('save restores projects, decisions, policies, queued orders and resources',()=>{
 const {GameData,SaveGame}=engine(),d=new GameData('UA',{scenario:'war2024'});d.invest('UA-1','agro');d.processProjects();d.queueRecruitment('UA-2','tanks',1);d.setPolicy('UA','social');d.decisions.push({type:'peace',from:'RU'});
 assert.equal(SaveGame.save(d),true);const loaded=SaveGame.load();assert.ok(loaded,SaveGame.error);const restored=GameData.restore(loaded.game);assert.equal(JSON.stringify(restored.serialize()),JSON.stringify(d.serialize()));restored.processProjects();assert.equal(restored.projects.length,0);
});
test('discard prevents lifecycle callbacks from resurrecting a save',()=>{const {GameData,SaveGame}=engine(),d=new GameData('UA');SaveGame.save(d);SaveGame.discard();assert.equal(SaveGame.save(d),false);assert.equal(SaveGame.load(),null);});
test('failed turns preserve the last complete save and cannot run again',()=>{
 const {GameData,GameLoop,SaveGame}=engine(),d=new GameData('UA');SaveGame.save(d);const before=JSON.stringify(SaveGame.load().game);
 const loop=Object.create(GameLoop.prototype);let calls=0;
 Object.assign(loop,{data:d,endTurnBtn:{},ui:{toast(){}},ai:{planTurn(){calls++;d.countries.UA.money=0;throw new Error('Injected turn failure');}}});
 loop.processTurn();assert.equal(loop.failed,true);assert.equal(loop.endTurnBtn.disabled,true);assert.equal(SaveGame.save(d),false);assert.equal(JSON.stringify(SaveGame.load().game),before);loop.processTurn();assert.equal(calls,1);
});
test('map fingerprint changes with geometry; such saves migrate and keep a backup',()=>{const {GameData,SaveGame,RegionsDB,localStorage}=engine();const d=new GameData('UA');d.countries.UA.money=12345678;d.turn=7;SaveGame.save(d);const old=SaveGame.mapId();RegionsDB['CA-6'].path+='M0,0Z';SaveGame.signature=null;assert.notEqual(SaveGame.mapId(),old);const loaded=SaveGame.load();assert.ok(loaded,SaveGame.error);assert.equal(SaveGame.migrated,true);assert.equal(loaded.game.turn,7);assert.equal(loaded.game.countries.UA[0],12345678);assert.ok(localStorage.getItem(SaveGame.BACKUP_KEY));});
test('saves from another map are rejected and retained',()=>{const {GameData,SaveGame,localStorage}=engine();const save=new GameData('UA').serialize();const regions={};for(const [id,r] of Object.entries(save.regions))regions['X'+id]=r;save.regions=regions;localStorage.setItem(SaveGame.KEY,JSON.stringify({map:'old',game:save}));assert.equal(SaveGame.load(),null);assert.ok(SaveGame.error);assert.ok(localStorage.getItem(SaveGame.KEY));});
test('v2 saves from the previous version migrate with defaults for new fields',()=>{const {GameData,SaveGame,localStorage}=engine();const d=new GameData('DE',{scenario:'war2024'});d.startWar('DE','PL');d.setOwner('PL-1','DE');const v3=d.serialize();const v2={v:2,player:'DE',cheat:false,scenario:'war2024',date:v3.date,turn:5,regions:{},countries:{},wars:v3.wars,truces:[],orders:{recruitment:[],attacks:[],movements:[],recon:[]},decisions:[],history:[],gameOver:false};for(const [id,r] of Object.entries(v3.regions))v2.regions[id]=r.slice(0,4);for(const [id,c] of Object.entries(v3.countries))v2.countries[id]=c.slice(0,7);localStorage.setItem(SaveGame.KEY,JSON.stringify({map:'1996:AD-1:ZW-9',savedAt:1,game:v2}));const loaded=SaveGame.load();assert.ok(loaded,SaveGame.error);const r=GameData.restore(loaded.game);assert.equal(r.regions['PL-1'].owner,'DE');assert.equal(r.turn,5);assert.ok(r.isAtWar('DE','PL'));assert.equal(r.countries.DE.policy,'balanced');assert.equal(r.difficulty,'normal');});
test('export produces a file that imports back identically',()=>{const {GameData,SaveGame}=engine();const d=new GameData('BR',{difficulty:'hard'});d.turn=3;const file=SaveGame.exportFile(d);assert.match(file.name,/br-turn3\.json$/);const back=GameData.restore(SaveGame.parse(file.text).game);assert.equal(SaveGame.migrated,false);assert.equal(JSON.stringify(back.serialize()),JSON.stringify(d.serialize()));assert.throws(()=>SaveGame.parse('{"nope":1}'));});
test('difficulty scales the player budget and AI caution',()=>{const {GameData,AI}=engine();const money=l=>new GameData('FR',{difficulty:l}).countries.FR.money;assert.ok(money('easy')>money('normal'));assert.ok(money('hard')<money('normal'));const easy=new AI(new GameData('FR',{difficulty:'easy'})),hard=new AI(new GameData('FR',{difficulty:'hard'}));assert.ok(easy.rule('ATTACK_MARGIN')>hard.rule('ATTACK_MARGIN'));assert.equal(new AI(new GameData('FR')).rule('AI_WAR_CHANCE'),0.05);});
test('corrupt state rejected before restoration',()=>{const {GameData}=engine(),save=JSON.parse(JSON.stringify(new GameData('UA').serialize()));save.regions['UA-1'][1][0]=-1;assert.throws(()=>GameData.restore(save));});
test('every playable country starts with a valid save and finite budget',()=>{
 const {GameData}=engine();const world=new GameData('UA');
 for(const country of Object.values(world.countries).filter(c=>c.playable)) {
  const d=new GameData(country.id),balance=d.countryBalance(country.id);
  assert.ok(Number.isFinite(balance.income-balance.expense),country.id);
  assert.doesNotThrow(()=>GameData.validateSave(d.serialize()),country.id);
 }
});
test('world control produces victory; loss of all land produces defeat',()=>{const {GameData}=engine(),d=new GameData('UA');for(const r of Object.values(d.regions))d.setOwner(r.id,'UA');d.applyEndOfTurn();assert.equal(d.outcome,'victory');assert.equal(d.campaignProgress().share,1);const lost=new GameData('UA');for(const r of [...lost.getCountryRegions('UA')])lost.setOwner(r.id,'RU');lost.applyEndOfTurn();assert.equal(lost.outcome,'defeat');});
test('broke AI still issues tactical orders',()=>{const {GameData,AI}=engine(),d=new GameData('UA',{scenario:'war2024'});d.turn=20;d.countries.RU.money=0;d.countries.RU.lastNetIncome=-1000000;const ai=new AI(d);let calls=0;ai.planWar=()=>calls++;ai.planTurn();assert.ok(calls>0);});
test('peace remains pending until an answer, decline is persisted, turn locked',()=>{const {GameData,GameLoop,SaveGame}=engine(),d=new GameData('UA',{scenario:'war2024'});d.decisions.push({type:'peace',from:'RU'});let dialog;const loop=Object.create(GameLoop.prototype);Object.assign(loop,{data:d,ui:{showDecision:o=>dialog=o},endTurnBtn:{},updateTopBarUI(){}});loop.afterSummary();assert.equal(d.decisions.length,1);assert.equal(loop.endTurnBtn.disabled,true);SaveGame.save(d);assert.equal(SaveGame.load().game.decisions.length,1);dialog.onDecline();assert.equal(SaveGame.load().game.decisions.length,0);assert.equal(loop.endTurnBtn.disabled,false);});
test('80-turn deterministic campaign preserves integer armies and loadable state',()=>{const {GameData,AI,SaveGame}=engine(),d=new GameData('US',{scenario:'war2024'}),ai=new AI(d);for(let t=0;t<80&&!d.gameOver;t++){ai.planTurn();d.processOrders();d.applyEndOfTurn();d.turn++;d.currentDate.setDate(d.currentDate.getDate()+7);ai.diplomacy();for(const r of Object.values(d.regions)){assert.ok(d.regionsByCountry[r.owner].includes(r.id));assert.ok(Object.values(r.army).every(n=>Number.isInteger(n)&&n>=0));}assert.ok(SaveGame.save(d));assert.ok(SaveGame.load(),SaveGame.error);}});
test('logistics unlocks isolated island expeditions, charges and refunds transports',()=>{const {GameData}=engine(),d=new GameData('UA');d.startWar('UA','NZ');assert.equal(d.getValidAttackTargets('UA-1').includes('NZ-1'),false);d.countries.UA.tech.marchSpeed=3;assert.equal(d.getValidAttackTargets('UA-1').includes('NZ-1'),true);const before=d.countries.UA.money,inf=d.countries.UA.influence;assert.equal(d.queueAttack('UA-1','NZ-1',{infantry:1}).ok,true);assert.equal(d.countries.UA.money,before-525000);d.makePeace('UA','NZ');assert.equal(d.orders.attacks.length,0);assert.equal(d.countries.UA.money,before);assert.equal(d.countries.UA.influence,inf);});
test('every sovereign region is a legal expedition target at maximum logistics',()=>{const {GameData}=engine(),d=new GameData('UA');d.countries.UA.tech.marchSpeed=3;for(const c of Object.values(d.countries))if(c.playable&&c.id!=='UA')d.startWar('UA',c.id);const targets=new Set(d.getValidAttackTargets('UA-1'));for(const r of Object.values(d.regions))if(d.countries[r.owner].playable&&r.owner!=='UA')assert.ok(targets.has(r.id));});
test('surrounded defenders are fully counted in battle losses',()=>{const {GameData}=engine(),d=new GameData('UA');d.startWar('UA','MD');const target=d.regions['MD-1'];for(const id of d.getNeighbors(target.id))if(d.regions[id].owner==='MD')d.setOwner(id,'RO');const from=d.getCountryRegions('UA').find(r=>d.getNeighbors(r.id).includes(target.id));from.army=d.emptyArmy();from.army.aviation=1000;target.army=d.emptyArmy();target.army.infantry=10;d.queueAttack(from.id,target.id,{aviation:1000});const logs=d.processOrders().logs;assert.equal(logs.find(x=>x.losses).losses.defender.infantry,10);});
test('world market conserves money and goods: sold equals bought',()=>{const {GameData,Economy,RESOURCES}=engine(),d=new GameData('DE');for(let t=0;t<6;t++){const out=Economy.runMarkets(d);const total=Object.values(out).reduce((a,r)=>a+r.money,0);assert.ok(Math.abs(total)<=Object.keys(out).length,'money '+total);for(const key of Object.keys(RESOURCES)){const sold=Object.values(out).reduce((a,r)=>a+r.res[key].sold,0),bought=Object.values(out).reduce((a,r)=>a+r.res[key].bought,0);assert.ok(Math.abs(sold-bought)<1e-6,key);assert.ok(Number.isFinite(d.market[key])&&d.market[key]>0);}}});
test('prices rise under shortage and fall under glut within the corridor',()=>{const {GameData,Economy,ECONOMY,RESOURCES}=engine(),d=new GameData('DE');for(const c of Object.values(d.countries))if(c.stock)c.stock.food=0;for(const r of Object.values(d.regions))r.resources.agro=0;for(let t=0;t<30;t++)Economy.runMarkets(d);assert.ok(d.market.food>RESOURCES.food.price*1.5);assert.ok(d.market.food<=RESOURCES.food.price*ECONOMY.PRICE_MAX);const g=new GameData('DE');for(const r of Object.values(g.regions))r.resources.industry*=5;for(let t=0;t<30;t++)Economy.runMarkets(g);assert.ok(g.market.goods<RESOURCES.goods.price*0.8);assert.ok(g.market.goods>=RESOURCES.goods.price*ECONOMY.PRICE_MIN-1);});
test('hunger lowers loyalty, shrinks population and army; broke countries cannot buy',()=>{const {GameData}=engine(),d=new GameData('UA');const ua=d.countries.UA;ua.money=-1e9;ua.stock.food=0;for(const r of d.getCountryRegions('UA'))r.resources.agro=0;const pop=d.getCountryRegions('UA').reduce((a,r)=>a+r.population,0),army=d.getCountryRegions('UA').reduce((a,r)=>a+r.army.infantry,0);const {events}=d.applyEndOfTurn();assert.ok(ua.economy.sat.food<0.8);assert.equal(ua.economy.res.food.bought,0);assert.ok(events.some(e=>e.type==='shortage'));d.applyEndOfTurn();assert.ok(d.getCountryRegions('UA').reduce((a,r)=>a+r.population,0)<pop);assert.ok(d.getCountryRegions('UA').reduce((a,r)=>a+r.army.infantry,0)<army);assert.ok(d.getCountryRegions('UA').every(r=>r.loyalty<1));});
test('keep mode stores surplus instead of selling; war blockade limits trade',()=>{const {GameData,Economy}=engine(),d=new GameData('KZ');assert.equal(d.setTrade('KZ','food','keep'),true);assert.equal(d.setTrade('KZ','food','hoard'),false);const before=d.countries.KZ.stock.food,out=Economy.runMarkets(d);assert.equal(out.KZ.res.food.sold,0);assert.ok(d.countries.KZ.stock.food>before);const w=new GameData('KZ');const peace=Economy.runMarkets(new GameData('KZ')).KZ.res.energy.sold;w.startWar('KZ','UZ');const war=Economy.runMarkets(w).KZ.res.energy.sold;assert.ok(war<peace*0.7);});
test('economy survives save, restore and migration from saves without it',()=>{const {GameData,SaveGame}=engine(),d=new GameData('UA');d.setTrade('UA','goods','keep');d.applyEndOfTurn();const back=GameData.restore(JSON.parse(JSON.stringify(d.serialize())));assert.equal(JSON.stringify(back.serialize()),JSON.stringify(d.serialize()));assert.equal(back.countries.UA.trade.goods,'keep');const old=d.serialize();delete old.market;for(const c of Object.values(old.countries))c.length=9;for(const r of Object.values(old.regions))r.length=6;const migrated=GameData.restore(GameData.migrateSave(old));assert.ok(migrated.countries.UA.stock.food>0);assert.equal(migrated.countries.UA.trade.food,'sell');});
test('tech tree: locked units, research takes turns, unlocks, cancel refunds',()=>{const {GameData,TECH_TREE}=engine(),d=new GameData('DE');const de=d.countries.DE;de.money=1e9;const r=d.getCountryRegions('DE')[0].id;assert.equal(d.queueRecruitment(r,'drones',1).ok,false);assert.equal(d.startResearch('DE','ewar').ok,false);assert.equal(d.startResearch('DE','drones').ok,true);assert.equal(de.money,1e9-TECH_TREE.drones.cost);assert.equal(d.startResearch('DE','medicine').ok,false);for(let i=1;i<TECH_TREE.drones.turns;i++){d.applyEndOfTurn();d.turn++;assert.equal(d.queueRecruitment(r,'drones',1).ok,false);}const {events}=d.applyEndOfTurn();d.turn++;assert.ok(events.some(e=>e.type==='tech'));assert.equal(d.queueRecruitment(r,'drones',1).ok,true);assert.equal(d.startResearch('DE','drones').ok,false);
 const m=de.money;d.startResearch('DE','medicine');assert.equal(d.cancelResearch('DE'),TECH_TREE.medicine.cost);assert.equal(de.money,m);d.startResearch('DE','medicine');d.turn++;assert.equal(d.cancelResearch('DE'),TECH_TREE.medicine.cost/2);});
test('modernization gets pricier each step and stops at the cap',()=>{const {GameData,MODERNIZATION}=engine(),d=new GameData('DE');d.countries.DE.money=1e12;let last=0;for(let l=1;l<MODERNIZATION.MAX;l++){const c=d.techCost('DE','tanks');assert.ok(c>last);last=c;assert.equal(d.research('DE','tanks').ok,true);}assert.equal(d.techCost('DE','tanks'),null);assert.equal(d.research('DE','tanks').ok,false);assert.equal(d.techCost('DE','stealth'),null);assert.ok(Math.abs(d.techMultiplier('DE','tanks')-(1+(MODERNIZATION.MAX-1)*MODERNIZATION.STEP))<1e-9);});
test('tech effects: fewer losses, stronger defense, more food, logistics',()=>{const {GameData,Economy,Tech}=engine(),a=new GameData('UA'),b=new GameData('UA');const t=a.regions['UA-1'];const base=a.defensePower(t,{infantry:10});Tech.grant(b.countries.UA,'fortify');assert.ok(b.defensePower(b.regions['UA-1'],{infantry:10})>base*1.14);const food=Economy.flows(a,'UA').food.prod;Tech.grant(b.countries.UA,'agrotech');assert.ok(Economy.flows(b,'UA').food.prod>food*1.14);Tech.grant(b.countries.UA,'logistics2');assert.equal(b.countries.UA.tech.marchSpeed,3);
 const fight=med=>{const d=new GameData('UA');d.startWar('UA','MD');if(med)Tech.grant(d.countries.UA,'medicine');const from=d.getCountryRegions('UA').find(r=>d.getNeighbors(r.id).includes('MD-1'));from.army=d.emptyArmy();from.army.infantry=100;d.regions['MD-1'].army=d.emptyArmy();d.regions['MD-1'].army.infantry=60;d.queueAttack(from.id,'MD-1',{infantry:100});return d.processOrders().logs.find(l=>l.losses).losses.attacker.infantry;};assert.ok(fight(true)<fight(false));});
test('research survives save and old logistics levels become technologies',()=>{const {GameData}=engine(),d=new GameData('DE');d.countries.DE.money=1e9;d.startResearch('DE','powergrid');d.research('DE','infantry');const back=GameData.restore(JSON.parse(JSON.stringify(d.serialize())));assert.equal(JSON.stringify(back.serialize()),JSON.stringify(d.serialize()));assert.equal(back.countries.DE.research.id,'powergrid');const old=d.serialize();for(const c of Object.values(old.countries)){c.length=9;}old.countries.DE[3].marchSpeed=3;const m=GameData.restore(GameData.migrateSave(old));assert.ok(m.countries.DE.techs.includes('logistics2'));assert.equal(m.countries.DE.research,null);});
test('rich AI spends surplus on science instead of hoarding',()=>{const run=science=>{const {GameData,AI}=engine(),d=new GameData('DE'),ai=new AI(d);if(!science)ai.planScience=()=>{};d.countries.CN.money=5e8;for(let t=0;t<10;t++){ai.planTurn();d.processOrders();d.applyEndOfTurn();d.turn++;}return d.countries.CN;};const cn=run(true),hoard=run(false);assert.ok(cn.techs.length>=3);assert.ok(Object.keys(cn.tech).some(k=>k!=='marchSpeed'&&cn.tech[k]>1));assert.ok(cn.money<hoard.money-1e8,`${cn.money} vs ${hoard.money}`);});
